### ISSUE TITLE
RR3300 graphics

### ISSUE THREAD

**Issue by justgans** [RoxanneSHS/ROTerrorEE#1]
Hello Roxanne! 

Please can u check RR3300 area resources 'cause i've some graphics issues there. All other iwd areas i've checked are ok. Mod is installed on v2.3.67.3 (GOG)

this one:

https://www.youtube.com/watch?v=pELfjhOgOQM

I'm tryin' fix all issues in current setup for future gaming but this one i can't :(

Thanks!

**Comment by RoxanneSHS** [comment]
I see the issue in my game as well. I will investigate.

**Comment by justgans** [comment]
thanks a lot :)

**Comment by RoxanneSHS** [comment]
I have no quick solution for it - it is a problem with the old original TIS file.
I have found this one working in my game. It is an interim but you can try it. Just drop it into your bg2ee/override
https://www.dropbox.com/s/5n1hbg5rft63bal/RR3300.TIS?dl=0
(Maybe before you do, you may want to rename the existing one to something else, just in case there is need to restore it.)

**Comment by RoxanneSHS** [comment]
Here is a second attempt
https://www.dropbox.com/s/vnrc44kbg18fco7/RR3300Tis.zip?dl=0
This is EE compatible but may show some glitch around closed doors - but far better than original version.

**Comment by justgans** [comment]
Roxanne, it's excellent! 

Small graphics bugs are not important only that ugly lines were the problem ^^)

https://www.youtube.com/watch?v=rYRWZHUhupk

Thanks for quick support, you're my hero! =)
